-

diff --git a/bin/botnet_ctl b/bin/botnet_ctl
--- a/bin/botnet_ctl
+++ b/bin/botnet_ctl
@@ -2,6 +2,10 @@
 
 cmd=$1
 
+help() {
+echo 
+}
+
 function checkout() {
 IP=$1
 echo "checkout $IP"
@@ -57,7 +61,7 @@ ssh $IP "cd us; /etc/init.d/us-wallet restart"
 
 nodes="10.84.172.66 10.84.172.55 10.84.172.54 10.84.172.52 10.84.172.50"
 
-if [ "_$cmd" == "_bots" ]; then
+if [ "_$cmd" == "_bots" ]; then  # Print the IP addresses og the bots
     for n in $nodes; do
         echo $n
     done
@@ -125,6 +129,18 @@ echo $n
         stopw $n
     done
 fi
+if [ "_$cmd" == "_restartw" ]; then
+    for n in $nodes; do
+echo $n
+        restartw $n
+    done
+fi
+if [ "_$cmd" == "_restartg" ]; then
+    for n in $nodes; do
+echo $n
+        restartg $n
+    done
+fi
 if [ "_$cmd" == "_restart" ]; then
     for n in $nodes; do
 echo $n
@@ -160,6 +176,23 @@ echo -n "$n - "
         ssh $n "cat ~/.us/gov/blocks/head"
     done
 fi
+if [ "_$cmd" == "_ping" ]; then
+    for n in $nodes; do
+        us-wallet -whost $n ping
+    done
+fi
+if [ "_$cmd" == "_rm_auth_devices" ]; then  #deletes device file wallet/d . require wallet daemon restart
+    for n in $nodes; do
+echo -n "$n - "
+        ssh $n "rm ~/.us/wallet/d"
+    done
+fi
+if [ "_$cmd" == "_cat_auth_devices" ]; then  #shows auth device ids
+    for n in $nodes; do
+echo -n "$n - "
+        ssh $n "cat ~/.us/wallet/d"
+    done
+fi
 if [ "_$cmd" == "_bin" ]; then
     for n in $nodes; do
 echo -n "$n - "
@@ -192,7 +225,17 @@ echo -n "$n - "
         checkout $n
     done
 fi
-
+if [ "_$cmd" == "_" ]; then
+MY_PATH=`dirname "$0"`
+MY_PATH=`( cd "$MY_PATH" && pwd )`
+if [ -z "$MY_PATH" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  exit 1  # fail
+fi
+    echo "commands:"
+    cat  $MY_PATH/botnet_ctl | grep "if \[ \"_\$cmd\"" | grep -v "\"_\"" | sed "s/.* == \"_\(.*\)\" ]; then *\(.*\)/* \1 - \2/" | sort | nl
+fi
 
 
 wait
