improve bash code

diff --git a/bin/user_daemons_ctl b/bin/user_daemons_ctl
--- a/bin/user_daemons_ctl
+++ b/bin/user_daemons_ctl
@@ -1,31 +1,33 @@
 #!/bin/bash
 
-home=`mktemp -d`
 
-#---govd---
-#gov='g'
-LD_LIBRARY_PATH=gov govd/us-govd -d -home $home -genesis 127.0.0.1   #---> gov ???
-if [ $? -eq 0 ]; then
-    echo "govd-> PASS"
+#-------------------------start()----------------------------------------
+start() {
+
+	home=`mktemp -d`
+	echo "home dir is $home"
+
+	#---govd---
+	LD_LIBRARY_PATH=gov govd/us-govd -d -home $home -genesis 127.0.0.1
+       
+      if [ $? -eq 0 ]; then
+    	echo "govd-> PASS"
  
-else
-    echo "govd-> FAIL"
+	else
+    	echo "govd-> FAIL"
 	exit 1;
-
-fi
+     fi
 
 ls $home
 
-
-#---------------------------------------------------------------------
-
+#-------
 
 g_port=16671
 w_port=16673
 
 for value in {1..3}
 do                                                                 #
-   LD_LIBRARY_PATH=gov govd/us-govd -d -home $home/$iGovHome -p $g_port 2>&1 >/dev/null &
+   LD_LIBRARY_PATH=gov govd/us-govd -d -home $home -p $g_port 2>&1 >/dev/null &
    sleep 1
    pid_g=`ps ax | grep govd | grep -v grep | awk '{print $1}' | sort | tail -n1`
    echo "--------------------------------------------------"
@@ -43,9 +45,37 @@ do                                                                 #
 let g_port--
 done
 
+}
 
 
 
-#---------------------------------------------------------------------
+
+
+#-----------------------stop()----------------------------------------
+stop() {
+	
+	killall us-walletd us-govd
+}
+
+
+
+
+
+
+
+#----------------------case-----------------------------------------
+case "$1" in   
+	start)   start ;;  
+	stop)    stop ;;
+	restart) stop; start ;;
+    	*) echo "usage: $0 start|stop|restart" >&2
+       exit 1
+       ;;
+esac
+
+
+
+
+
 
 
